version: '3.1'
services:
  app:
    container_name: carparts
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - NODE_ENV=productive
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"