version: "3"
services:
  app:
    container_name: carparts
    restart: always
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./data/files:/app/data/files
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
