version: '3.1'

networks:
  apps:

services:
  carparts:
    container_name: carparts
    restart: always
    build: .
    ports:
      - "3000:3000"
    networks:
      - apps
    depends_on:
      - mongo    
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - apps