version: '3.1'

networks:
  wpnet:

services:
  wordpress:
    container_name: wp
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: rM4c6WRW
      WORDPRESS_DB_NAME: wordpress_db
    ports:
      - 8080:80
    volumes:
      - "./html:/var/www/html"
    depends_on:
      - mysql    
    networks:
      - wpnet
      
  mysql:
    container_name: wpdb
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rnWr9cpq
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: rM4c6WRW
      MYSQL_DATABASE: wordpress_db
    volumes:
      - "./database:/var/lib/mysql"
    networks:
      - wpnet
